; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n8r2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r2
framework = arduino

monitor_speed = 9600
upload_speed = 921600

lib_deps =
    GyverLibs/GyverHX711
    GyverLibs/GyverDS18
    GyverLibs/FileData
    GyverLibs/uButton
