; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 9600
upload_speed = 921600

lib_deps =
    GyverLibs/GyverHX711
    GyverLibs/GyverDS18
    GyverLibs/FileData
    GyverLibs/uButton


[env:esp32-s3-SIM800L]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r2
framework = arduino
    ; здесь исключаем весь код, связанный с WiFi

[env:esp32-s3-WiFi]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r2
framework = arduino
extra_scripts = pre:scripts/embed_web.py
    ; Здесь исключаем код, связанный с SIM800L

    lib_deps =
        ${env.lib_deps}
        https://github.com/mathieucarbou/ESPAsyncWebServer.git
        https://github.com/mathieucarbou/AsyncTCP.git


[env:native-tests]
platform = native
build_flags = -std=c++17 -DCALIB_STORAGE=0
build_src_filter = -<*> +<../test/test_calibration>
